---
title: "0024_UCI_BurnsReserve"
author: "Emily Marie Purvis"
date: "2026-08-10"
output: html_document
---

```{r}

# Load libraries

library(tidyverse)
library(sf)

```

Import data

```{r}

# import data

data <- st_read("C:/Users/empurvis/Box/FOCAL/ofo-field-data/1_received-data/0024/S123_69d33483b88146e5a856a7c2df9dcabe_SHP/survey.shp")


```

Plot polygons

```{r}

# not sure if we are counting each grid cell as a plot, or counting the whole project as one plot

## if each grid cell is a plot ##

# all of the survey points are in specific grid numbers, but we don't have the grid. going to use the points to generate hulls that approximate the grid locations.

grid_col <- "gridcell"

# convert to UTM

data_utm <- st_transform(data, 32611)

polys_convex <- data_utm |>
  group_by(.data[[grid_col]]) |>
  summarize(geometry = st_convex_hull(st_union(geometry)), .groups = "drop")

#st_write(polys_convex, "C:/Users/empurvis/Desktop/grid_convex_hulls.gpkg", delete_layer = TRUE)

# there are some errors in the dataset: 1. the point labelled "32-33" is clearly within polygon 32, 2. there's a tree labelled "27" that should be "37"

# 1: relabel 32-33

data_utm$gridcell[data_utm$gridcell =="32-33"] <- 32 

# 2: find the tree that is labeled 27 but should be 37

cell27 <- data_utm |> filter(gridcell == 27) # sf object of all 27s

cell37 <- data_utm |> filter(gridcell == 37) # sf object of all 37s

nn <- st_nearest_feature(cell27, cell37) # nearest neighbor list

closest_37 <- cell37[nn, , drop = FALSE]

dist <- as.numeric(st_distance(st_geometry(cell27), st_geometry(closest_37)))

cell27_closest <- cell27[which.min(dist), , drop = FALSE] # got it: it's globalid "dba7680a-4d6a-4e25-b811-3274592d74af"

data_utm$gridcell[data_utm$globalid =="dba7680a-4d6a-4e25-b811-3274592d74af"] <- 37 

# re-generate polygons

polys_convex <- data_utm |>
  group_by(.data[[grid_col]]) |>
  summarize(geometry = st_convex_hull(st_union(geometry)), .groups = "drop")

# one of the grid cells only has two plots, so the code generates a line instead of a polygon. going to extract the linestring from the poly sf object and buffer it into a polygon

linestring_only <- polys_convex[st_geometry_type(polys_convex) %in% ("LINESTRING"), ] # extract the line from the rest of the dataset

linestring_only_buffered <- st_buffer(linestring_only, 1) # buffering by 1 meter into a polygon

polygons_only <- polys_convex[st_geometry_type(polys_convex) %in% ("POLYGON"), ] # dataset of the original polygons

polys_all <- rbind(linestring_only_buffered, polygons_only) # merge the buffered linestring with the original polygons

polys_all <- st_transform(polys_all, crs = 4326) # convert back to WGS84

# assign OFO plot ID numbers to the polygons, starting with 0296

polys_all$OFO_plot_ID <- "" # create new column

polys_all$OFO_plot_ID[polys_all$gridcell =="19"] <- 0296
  
polys_all$OFO_plot_ID[polys_all$gridcell =="23"] <- 0297

polys_all$OFO_plot_ID[polys_all$gridcell =="24"] <- 0298

polys_all$OFO_plot_ID[polys_all$gridcell =="26"] <- 0299

polys_all$OFO_plot_ID[polys_all$gridcell =="27"] <- 0300
  
polys_all$OFO_plot_ID[polys_all$gridcell =="28"] <- 0301
  
polys_all$OFO_plot_ID[polys_all$gridcell =="29"] <- 0302

polys_all$OFO_plot_ID[polys_all$gridcell =="31"] <- 0303
  
polys_all$OFO_plot_ID[polys_all$gridcell =="32"] <- 0304
  
polys_all$OFO_plot_ID[polys_all$gridcell =="33"] <- 0305

polys_all$OFO_plot_ID[polys_all$gridcell =="36"] <- 0306

polys_all$OFO_plot_ID[polys_all$gridcell =="37"] <- 0307

polys_all$OFO_plot_ID[polys_all$gridcell =="38"] <- 0308
  
polys_all$OFO_plot_ID[polys_all$gridcell =="39"] <- 0309
  
polys_all$OFO_plot_ID[polys_all$gridcell =="43"] <- 0310

# drop gridcell column and export

polys <- polys_all[,-1] # drop column

st_write(polys, "C:/Users/empurvis/Desktop/UCI_burns_multiple_polys.gpkg") # for my own inspection purposes- this line can be deleted later

# for(i in 1:nrow(polys)) {
#   polygon_current <- polys[i, ]
#   plot_id_current = polygon_current$OFO_plot_ID
#   st_write(polygon_current, paste0("C:/Users/empurvis/Box/FOCAL/ofo-field-data/2_standardized-data/field-plot-boundaries", plot_id_current, ".gpkg"))
# } # export

## if the whole site is one plot ##

union <- st_union(st_geometry(data_utm)) # union

singular_poly <- st_convex_hull(union) # convex hull

singular_poly <- st_sf(geometry = singular_poly) # make into sf object

singular_poly$OFO_plot_ID <- 0296 # add OFO plot ID number

# st_write(singular_poly, "C:/Users/empurvis/Desktop/UCI_burns_singular_poly.gpkg") # for my own inspection purposes- this line can be deleted later

# for(i in 1:nrow(singular_poly)) {
#   polygon_current <- singular_poly[i, ]
#   plot_id_current = polygon_current$OFO_plot_ID
#   st_write(polygon_current, paste0("C:/Users/empurvis/Box/FOCAL/ofo-field-data/2_standardized-data/field-plot-boundaries", plot_id_current, ".gpkg"))
# } # export

```

Plot data

```{r}

## if each grid cell is a plot ##

# survey date approx

polys_all$survey_date_approx <- "TRUE"

# survey date

polys_all$survey_date <- ""

polys_all$survey_date[polys_all$gridcell =="19"] <- 20240723
  
polys_all$survey_date[polys_all$gridcell =="23"] <- 20240723

polys_all$survey_date[polys_all$gridcell =="24"] <- 20240722

polys_all$survey_date[polys_all$gridcell =="26"] <- 20240624

polys_all$survey_date[polys_all$gridcell =="27"] <- 20240716
  
polys_all$survey_date[polys_all$gridcell =="28"] <- 20240714
  
polys_all$survey_date[polys_all$gridcell =="29"] <- 20240722

polys_all$survey_date[polys_all$gridcell =="31"] <- 20240624
  
polys_all$survey_date[polys_all$gridcell =="32"] <- 20240624
  
polys_all$survey_date[polys_all$gridcell =="33"] <- 20240624

polys_all$survey_date[polys_all$gridcell =="36"] <- 20240624

polys_all$survey_date[polys_all$gridcell =="37"] <- 20240624

polys_all$survey_date[polys_all$gridcell =="38"] <- 20240703
  
polys_all$survey_date[polys_all$gridcell =="39"] <- 20240708
  
polys_all$survey_date[polys_all$gridcell =="43"] <- 20240704

# plot shape

polys_all$plot_shape <- "irregular"

# plot area- make sure this is in UTMs so the result is in square meters

polys_all <- st_transform(polys_all, crs = 32611) # convert to UTMs if needed

polys_all$plot_area <- as.numeric(st_area(polys_all))

# subplots

polys_all$subplots <- "FALSE"

polys_all$subplot_shape <- ""

polys_all$subplot_area <- ""

# includes snags

polys_all$includes_snags <- "TRUE"

# includes damage

polys_all$includes_damage <- "FALSE"

polys_all$damage_codes_inspected <- ""

# forest type

polys_all$forest_type <- "185 – Pinyon juniper woodland"

# columns that we don't have values for

polys_all$canopy_cover <- ""

polys_all$min_dbh <- ""

polys_all$min_dbh_live <- ""

polys_all$max_dbh_of_primary_trees <- ""

polys_all$min_ht <- ""

polys_all$min_dbh_ohvis <- ""

polys_all$min_ht_ohvis <- ""

# plot latitude and plot longitude

polys_all <- st_transform(polys_all, crs = 4326) # convert to WGS84 if needed

polys_centroids <- st_centroid(polys_all) # find centroid points

centroids_coords <- st_coordinates(polys_centroids) # extract centroid coordinates

polys_all$plot_longitude <- centroids_coords[, "X"]

polys_all$plot_latitude <- centroids_coords[, "Y"]

# number of overhead visible trees excluded

polys_all$num_ohvis_trees_excluded <- "unknown" # confirm this with Derek

# contributor plot ID

polys_all$contributor_plot_id <- polys_all$gridcell



## if the whole site is one plot ##

singular_poly$survey_date_approx <- "TRUE"

singular_poly$survey_date <- 20240710

singular_poly$plot_shape <- "irregular"

singular_poly <- st_transform(singular_poly, crs = 32611) # convert to UTMs if needed to calculate area

singular_poly$plot_area <- as.numeric(st_area(singular_poly))

singular_poly$subplots <- "FALSE" # maybe? or maybe we're counting the grid cells as subplots? if so, can use the area functions above to find subplot areas. however, there's only one cell for subplot area in the google sheet- it assumes all subplots in a plot have the same area, which is not true here. 

singular_poly$subplot_shape <- ""

singular_poly$subplot_area <- ""

singular_poly$includes_snags <- "TRUE"

singular_poly$includes_damage <- "FALSE"

singular_poly$damage_codes_inspected <- ""

singular_poly$forest_type <- "185 – Pinyon juniper woodland"

singular_poly$canopy_cover <- ""

singular_poly$min_dbh <- ""

singular_poly$min_dbh_live <- ""

singular_poly$max_dbh_of_primary_trees <- ""

singular_poly$min_ht <- ""

singular_poly$min_dbh_ohvis <- ""

singular_poly$min_ht_ohvis <- ""

singular_poly <- st_transform(polys_all, crs = 4326) # convert to WGS84 if needed to calculate plot latitude and longitude

poly_centroid <- st_centroid(singular_poly) # find centroid point

centroid_coords <- st_coordinates(poly_centroid) # extract centroid coordinates

singular_poly$plot_longitude <- centroid_coords[, "X"]

singular_poly$plot_latitude <- centroid_coords[, "Y"]

singular_poly$num_ohvis_trees_excluded <- "unknown" # confirm this with Derek

singular_poly$contributor_plot_id <- "" # just one plot in the dataset, no plot ID number

```

Subplot data

```{r}

# if we're counting the whole site as one plot and the grid cells as subplots, need to generate data to fill out the subplot tab of the google sheet

```


Tree data

```{r}

# OFO plot ID numbers

# IF THE GRID CELLS ARE SEPARATE PLOTS

# starting with the "data_utm" data.frame because I changed two erroneous gridcell errors there earlier

trees <- data_utm

trees$OFO_plot_ID <- ""

trees <- trees %>% mutate(
    OFO_plot_ID = case_when(
      gridcell == "19" ~ "0296",
      gridcell == "23" ~ "0297",
      gridcell == "24" ~ "0298",
      gridcell == "26" ~ "0299",
      gridcell == "27" ~ "0300",
      gridcell == "28" ~ "0301",
      gridcell == "29" ~ "0302",
      gridcell == "31" ~ "0303",
      gridcell == "32" ~ "0304",
      gridcell == "33" ~ "0305",
      gridcell == "36" ~ "0306",
      gridcell == "37" ~ "0307",
      gridcell == "38" ~ "0308",
      gridcell == "39" ~ "0309",
      gridcell == "43" ~ "0310")
    )

# IF THE WHOLE SITE IS ONE PLOT

trees$OFO_plot_ID <- "0296"

# IF THE WHOLE SITE IS ONE PLOT, NEED TO ADD SUBPLOT NUMBERS FOR THE GRID CELLS

# tree latitude and tree longitude

# we want WGS84, EPSG 4326, need to change the CRS of the sf object

trees <- st_transform(trees, crs = 4326)

# extract the geometry features into columns of lat and long, then merge back into the spatial data frame

trees_coords <- data.frame(trees$'globalid', st_coordinates(trees[,1], st_coordinates(trees[,2]))) %>% rename (tree_lon=X, tree_lat=Y, globalid=trees.globalid)

trees <- full_join(trees, trees_coords, by="globalid")

# tree species

# according to the UCI Burns Reserve website (https://burns.ucnature.org/species-lists/), the only juniper species on the site is the California juniper (Juniperus californica), the pinon pine species on the site is the singleleaf pinon pine (Pinus monophylla), and the only oak species on the site is the desert scrub oak (Quercus cornelius-mulleri)

# FIA codes: 982 = joshua tree, 62 = juniper, 133 = pinon. Despite lots of searching I can't track down a code for the desert scrub oak, so I'll substitute the USDA plant code: QUCO7

trees$species <- ""

trees <- trees %>% mutate(
    species = case_when(
      tree_speci == "Pinon Pine" ~ "133",
      tree_speci == "Joshua Tree" ~ "982",
      tree_speci == "Juniper" ~ "62",
      tree_speci == "Oak" ~ "QUCO7"))

trees$species[trees$tree_spe_1 =="Dead shrub"] <- "0" # code for unknown species

trees$species[trees$tree_spe_1 =="Juniper"] <- "62"

trees$species[trees$tree_spe_1 =="Oak"] <- "QUCO7"

# growth form (all trees except 1 shrub in dataset)

trees$growth_form <- "tree"

trees$growth_form[trees$tree_spe_1 =="Dead shrub"] <- "shrub"

# live/dead

trees$live_dead <- ""

trees <- trees %>% mutate(
    live_dead = case_when(
      tree_statu == "Alive" ~ "L",
      tree_statu == "Alive,Dead" ~ "M",
      tree_statu == "Alive,Unhealthy" ~ "M",
      tree_statu == "Dead" ~ "D",
      tree_statu == "Unhealthy" ~ "M",
      tree_statu == "Unhealthy,Alive" ~ "M",
      tree_statu == "Unsure" ~ "M"))

# notes

trees$notes <- trees$other_note

trees$notes[is.na(trees$notes)] <- ""

# remove downed trees, we only want live and dead standing trees

trees <- trees[trees$tree_struc != "Downed", ] # went from 266 trees to 208 trees. there are still some marginal cases in here (e.g. clumps of trees with one standing and one downed). 

# contributor tree ID

trees$contributor_tree_id <- trees$globalid

# OFO columns that are empty in our dataset

trees$plotid2 <- ""

trees$subplotid <- "" # only if we don't make the grid cells into subplots

trees$height <- ""

trees$height_allometric <- ""

trees$height_above_plot <- ""

trees$dbh <- ""

trees$crown_position <- ""

trees$ohvis <- ""

trees$crown_ratio <- ""

trees$crown_ratio_compacted <- ""

trees$height_to_crown <- ""

trees$height_to_needle <- ""

trees$scorch_height <- ""

trees$percent_prefire_crown_green <- ""

trees$percent_postfire_crown_green <- ""

trees$live_crown_class <- ""

trees$crown_width_1 <- ""

trees$crown_width_2 <- ""

trees$crown_width_allometric <- ""

trees$decay_class <- ""

trees$damage1 <- ""

trees$damage2 <- ""

trees$damage3 <- ""

trees$damage4 <- ""

trees$damage5 <- ""

trees$distance_to_pith <- ""

trees$distance_to_face <- ""

trees$azimuth <- ""

# select columns and put them in order

trees_for_export <- trees[, c("OFO_plot_ID", "plotid2", "subplot_id", "tree_lat", "tree_lon", "height", "height_allometric", "height_above_plot", "dbh", "species", "growth_form", "live_dead", "crown_position", "ohvis", "crown_ratio", "crown_ratio_compacted", "height_to_crown", "height_to_needle", "scorch_height", "percent_prefire_crown_green", "percent_postfire_crown_green", "live_crown_class", "crown_width_1", "crown_width_2", "crown_width_allometric", "decay_class", "damage1", "damage2", "damage3", "damage4", "damage5", "distance_to_pith", "distance_to_face", "azimuth", "contributor_tree_id", "notes" )]

# export

write.csv(trees, "C:/Users/empurvis/Box/FOCAL/ofo-field-data/1_received-data/0024/data/UCIBurns_trees_processed_for_OFO.csv", row.names = FALSE, na = "")

```


