---
title: "OHDS_Trees"
author: "Victoria Mattsson"
date: "2025-04-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load Packages
```{r}

library(dplyr)
library(tidyverse)
library(readxl)

```

Load and merge datasets
```{r}

# Load Data

treesraw <- read_csv("/Users/Victoria/Documents/OFO/OHDS_StemPlots.csv") # 6206 rows
coordsraw <- read_excel("/Users/Victoria/Documents/OFO/StemCoordinates_DataOHDS.xlsx") # 13658 rows, has some additional comments


# Reclassify plot ID's, assign unique ID

trees <- treesraw %>% mutate(
    plot_id = case_when(
      PLOT == "Bait_405" ~ "0270",
      PLOT == "Clavicle_302" ~ "0271",
      PLOT == "Fresca_202" ~ "0272",
      PLOT == "Fulton_601" ~ "0273",
      PLOT == "Rail_103" ~ "0274",
      PLOT == "Snow_805" ~ "0275",
      PLOT == "Triton_703" ~ "0276"),
    unique_id = paste(plot_id, Tree_no, Recruit, sep = "_"))

coords <- coordsraw %>% mutate(
    plot_id = case_when(
      Plot == "405" ~ "0270",
      Plot == "302" ~ "0271",
      Plot == "202" ~ "0272",
      Plot == "601" ~ "0273",
      Plot == "103" ~ "0274",
      Plot == "805" ~ "0275",
      Plot == "703" ~ "0276"),
    unique_id = paste(plot_id, Tree_no, RECRUIT, sep = "_"))


# Join datasets

trees <- left_join(trees, coords, by = "unique_id")
# joining the coords datasetisn't absolutely necessary, but it does contain some extra comments

```

Remove downed trees
```{r}

# remove downed trees, i.e. damage = uprooted down OR tree class = down dead
trees <- subset(trees, (DamA != "UR" | is.na(DamA)) & (TC != 22 | is.na(TC))) # minus 1 UR tree and 256 down dead trees
# 5949 rows total now

# Maybe: remove trees with tree_no over 9000? emily says these were logged in her olympic.rmd... not sure where this information came from though

# trees <- subset(trees, trees$Tree_no.x < 9000) # 86 would be removed, uncomment this code if confirm this is true

```

Standardize to OFO format
```{r}

# Reclassify column values and add columns

trees <- trees %>% mutate(
    tree_id = "",
    plot_id2 = "",
    subplot_id = "",
    height_allometric = "",
    height_above_plot_center = "",
    species = case_when(
      Species.x == "PSME" ~ "202",
      Species.x == "TSHE" ~ "263",
      Species.x == "UNCL" ~ "0", 
      Species.x == "ABAM" ~ "11",
      Species.x == "ALRU2" ~ "351",
      Species.x == "PISI" ~ "98",
      Species.x == "UNCLS" ~ "002", # unclassified softwood
      Species.x == "RHPU" ~ "RHPU", # does not have FIA or species-codes sheet code (Cascara)
      Species.x == "THPL" ~ "242",
      Species.x == "SASP" ~ "924",
      Species.x == "PREM" ~ "768",
      Species.x == "ACCI" ~ "ACECIR", # from OFO species-codes sheet
      Species.x == "ACMA3" ~ "312",
      Species.x == "TABR" ~ "231"), # assuming they really meant TABR2 (pacific yew)
    growth_form = "tree", # assume all are trees
    live_dead = case_when( 
      TC == "10" ~ "L", # live tree (leave tree)
      TC == "11" ~ "L", # ingrowth tree
      TC == "12" ~ "L", # new tree, missed at previous measurements
      TC == "13" ~ "L", # live tree not suitable for height/diameter curves or height growth
      TC == "21" ~ "D", # standing dead (snag)
      DamA == "DI" ~ "M"), # diseased/sick/dying -> marginal
    crown_position = case_when(
      CC == "7" ~ "1", 
      CC == "1" ~ "2", 
      CC == "2" ~ "3", 
      CC == "3" ~ "4", 
      CC == "4" | CC == "5" ~ "5", # labeled as overtopped if suppressed OR if understory (not sure if this should be same class)
      TRUE ~ ""), 
    ohvis = case_when(
      crown_position == 1 | crown_position == 2 | crown_position == 3 ~ "TRUE",
      crown_position == 4 | crown_position == 5 ~ "FALSE", 
      TRUE ~ ""),
    crown_ratio = "",
    crown_ratio_compacted = "",
    height_to_crown = pmin(HlcLeft, HlcRight, na.rm = TRUE), 
            # height to live crown measured for left and right side of trees -> take min
    height_to_needle = "",
    scorch_height = "",
    percent_prefire_crown_green = "",
    percent_postfire_crown_green = "",
    live_crown_class = "",
    crown_width_1 = (CWLeft + CWRight), # calculate by adding crown width left side and right side
    crown_width_2 = "",
    crown_width_allometric = "",
    decay_class = "",
    damage_1 = case_when(
      DamA == "FT" ~ "90004", # FT = forked top or stem -> 90004 = forked top
      DamA == "BT" ~ "90001", # BT = broken top -> 90001 broken top
      DamA == "CR" | DamA == "SW" | DamA == "XL" ~ "90006", # 90006 = crook or sweep <- 
      # CR = crook, SW = sweep, XL = excessive lean (no FIA damage code for this specifically)
      DamA == "DT" ~ "90002", # DT = dead top -> 90002 = dead top
      DamA == "SB" ~ "9011", # SB = basal bark damage -> 9011 = open wound
      TRUE ~ ""),
    damage_2 = "", # original dataset includes cols for dam 2 and 3 but none were recorded
    damage_3 = "",
    damage_4 = "",
    damage_5 = "",
    distance_to_pith = "", # distance and azimuth measurements complicated by ingrowth tagging methods
    distance_to_face = "", 
    azimuth = "",
    notes = case_when(
      !is.na(Comments.x) & !is.na(Comments.y) ~ paste(Comments.x, Comments.y, sep = ", "),
      !is.na(Comments.x) ~ Comments.x,
      !is.na(Comments.y) ~ Comments.y), # comments exist for both datasets -> combine into one 'notes' col
    corrected_error = "") %>% 
  rename(
    plot_id = plot_id.x,
    tree_lat = Y_Lat,
    tree_lon = X_Long,
    height = Ht,
    dbh = Post_Dbh,
    contributor_tree_id = Tree_no.x) %>%  # note that contributor did not use unique id's
  subset(select = c(
    tree_id, plot_id, plot_id2, subplot_id, tree_lat, tree_lon, height, height_allometric,
    height_above_plot_center, dbh, species, growth_form, live_dead, crown_position, ohvis, crown_ratio,
    crown_ratio_compacted, height_to_crown, height_to_needle, scorch_height, percent_prefire_crown_green,
    percent_postfire_crown_green, live_crown_class, crown_width_1, crown_width_2, crown_width_allometric,
    decay_class, damage_1, damage_2, damage_3, damage_4, damage_5, distance_to_pith, distance_to_face, azimuth, 
    contributor_tree_id, notes, corrected_error))

```

Export
```{r}

write.csv(trees, "/Users/Victoria/Documents/OFO/OHDS_trees_OFO.csv", row.names = FALSE, na = "")

```

